name: react_Action
on: [push]
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4 
      - name: Add NodeJS
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  test-job:
    needs: [lint-job]
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4 
      - name: Add NodeJS
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run test
        run: npm run test
  build-job:
    needs: [test-job]
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4 
      - name: Add NodeJS
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run code build
        run: npm run build 
